version: '3.8'

services:
  web:
    container_name: web
    build: ./
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    env_file:
      ./.env.dev

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
